function BatchJTtimeStartUp(app)

addpath(genpath(fullfile(pwd,"ExternalCode")));
addpath(genpath(fullfile(pwd,"matnwb")));

app.FileChoice_DropDown.Visible = "off";
app.FileChoice_DropDown.Enable = "off";
app.fileProcess_Label.Visible = "off";
app.SaveChoice_Button.Visible = "off";
app.MClustCurrentFile_Label.Text = "For all Files";
app.Flags.FileLoaded = 0;
app.Flags.DataLoaded = 0;

app.ProcessType_DropDown.Items = {'...', 'dropcnsampler', 'dropcspm', ...
    'background', 'spmult', 'mspy', 'osampler', 'spm2mult', 'lighton1', ...
    'lighton5', 'dropcspm_conc', 'Laser-triggered', 'Laser-Merouann', ...
    'dropcspm_hf', 'Working_memoy', 'Continuous', 'Laser-Kira', ...
    'Laser-Schoppa'};

app.LoadingProcess_DropDown.Items = {'...', ...
    'dropcspm', ...
    'laser (Ming)', ...
    'dropcnsampler', ...
    'laser (Merouann)', ...
    'dropc_conc', ...
    'dropcspm_hf', ...
    'continuous', ...
    'working_memory', ...
    'laser (Schoppa)'};

app.Flags.LoadMethod = 1;
app.Flags.OutputType = 2;
app.OutputText = "Starting Batch processing";
app.Flags.RunningWhat = 3;